In [1]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [14]:
#creating an array

arr1 = np.random.randn(4,4)
arr1

#array via multidimensional list
numbers = [list(range(1,5)), list(range(6,10)), list(range(11,15)), list(range(16,20))]
arr2 = np.array(numbers)

In [19]:
print(arr1)

print(arr2)

[[ 0.01110337 -0.28365862  1.23694156  0.96249878]
 [ 0.15336372 -1.0975439   1.22250656 -0.0859879 ]
 [-1.1130896   1.78264735  0.02553093 -0.12906654]
 [-1.00452316 -0.62680058  0.20894897 -0.14090766]]
[[ 1  2  3  4]
 [ 6  7  8  9]
 [11 12 13 14]
 [16 17 18 19]]


In [7]:
#Mathematical operations
arr1 * 10

array([[-11.36252052, -15.89473889,  -1.32289904,  13.81863341],
       [  4.86912231,  -3.91330506,  12.58727933, -14.5326011 ],
       [ -8.48319922,   7.18789641,   1.54567238,  -0.2826706 ],
       [  2.13491439,  -9.96139471,  17.16169196,  15.59992719]])

In [23]:
print(arr1 + arr1)

print(arr2 - arr1)

[[ 0.02220675 -0.56731724  2.47388311  1.92499756]
 [ 0.30672743 -2.19508781  2.44501313 -0.17197579]
 [-2.2261792   3.5652947   0.05106187 -0.25813308]
 [-2.00904632 -1.25360117  0.41789794 -0.28181532]]
[[ 0.98889663  2.28365862  1.76305844  3.03750122]
 [ 5.84663628  8.0975439   6.77749344  9.0859879 ]
 [12.1130896  10.21735265 12.97446907 14.12906654]
 [17.00452316 17.62680058 17.79105103 19.14090766]]


In [11]:
arr1.shape
arr1.dtype

dtype('float64')

In [22]:
#Scalar Multiplication
print(arr1*arr2)

#Scalar Division
print(arr1/arr2)

[[ 1.11033749e-02 -5.67317235e-01  3.71082467e+00  3.84999512e+00]
 [ 9.20182304e-01 -7.68280733e+00  9.78005252e+00 -7.73891069e-01]
 [-1.22439856e+01  2.13917682e+01  3.31902137e-01 -1.80693158e+00]
 [-1.60723706e+01 -1.06556099e+01  3.76108142e+00 -2.67724553e+00]]
[[ 0.01110337 -0.14182931  0.41231385  0.2406247 ]
 [ 0.02556062 -0.15679199  0.15281332 -0.00955421]
 [-0.10118996  0.14855395  0.00196392 -0.00921904]
 [-0.0627827  -0.03687062  0.01160828 -0.00741619]]


In [21]:
np.dot(arr1,arr2)

array([[27.31548928, 29.24237438, 31.16925947, 33.09614457],
       [ 5.63986616,  5.83220464,  6.02454313,  6.21688161],
       [ 7.79857011,  8.36459226,  8.9306144 ,  9.49663654],
       [-4.72141057, -6.28469301, -7.84797545, -9.41125788]])