In [1]:
import numpy as np

arr1 = np.random.randint(1,15, size=(4,5))

In [2]:
display(arr1)

array([[11,  9,  3, 14,  4],
       [ 6, 14, 11,  7,  4],
       [ 7, 11,  5,  4,  4],
       [ 5,  4, 10,  8,  3]])

In [3]:
arr2 = np.array([2,10,6,4,1])

In [4]:
print(arr1)

[[11  9  3 14  4]
 [ 6 14 11  7  4]
 [ 7 11  5  4  4]
 [ 5  4 10  8  3]]


In [5]:
arr1+arr2 #Addition along the rows

array([[13, 19,  9, 18,  5],
       [ 8, 24, 17, 11,  5],
       [ 9, 21, 11,  8,  5],
       [ 7, 14, 16, 12,  4]])

In [6]:
arr3 = np.array([3,1,9,7]).reshape(4,1)

In [7]:
arr1+arr3 #Addition along columns

array([[14, 12,  6, 17,  7],
       [ 7, 15, 12,  8,  5],
       [16, 20, 14, 13, 13],
       [12, 11, 17, 15, 10]])

In [17]:
#Broadcasting with higher dimension arrays

arr1 = np.random.randint(1,20, size=(4,5))
arr2 = np.random.randint(1,20, size=(4,5))
arr1_3d = arr1[:, np.newaxis, :]
arr2_3d = arr2[:, :, np.newaxis]
print(arr1_3d)

[[[19  4 19 16 18]]

 [[ 1  4 14 14 13]]

 [[19  7 19 13 14]]

 [[16 10  3 12  8]]]


In [10]:
arr1_3d.shape

(4, 1, 5)

In [20]:
arr2_3d

array([[[ 2],
        [ 4],
        [ 3],
        [13],
        [ 8]],

       [[14],
        [ 3],
        [ 7],
        [10],
        [ 7]],

       [[10],
        [12],
        [13],
        [18],
        [ 5]],

       [[17],
        [16],
        [11],
        [ 4],
        [ 4]]])

In [19]:
arr1_3d + arr2_3d

array([[[21,  6, 21, 18, 20],
        [23,  8, 23, 20, 22],
        [22,  7, 22, 19, 21],
        [32, 17, 32, 29, 31],
        [27, 12, 27, 24, 26]],

       [[15, 18, 28, 28, 27],
        [ 4,  7, 17, 17, 16],
        [ 8, 11, 21, 21, 20],
        [11, 14, 24, 24, 23],
        [ 8, 11, 21, 21, 20]],

       [[29, 17, 29, 23, 24],
        [31, 19, 31, 25, 26],
        [32, 20, 32, 26, 27],
        [37, 25, 37, 31, 32],
        [24, 12, 24, 18, 19]],

       [[33, 27, 20, 29, 25],
        [32, 26, 19, 28, 24],
        [27, 21, 14, 23, 19],
        [20, 14,  7, 16, 12],
        [20, 14,  7, 16, 12]]])

In [25]:
arr_ones = np.ones((5,5))

In [26]:
arr_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
arr_ones[:] = 25

In [28]:
arr_ones

array([[25., 25., 25., 25., 25.],
       [25., 25., 25., 25., 25.],
       [25., 25., 25., 25., 25.],
       [25., 25., 25., 25., 25.],
       [25., 25., 25., 25., 25.]])